import { api, getConfig, listMembers, saveMember, deleteMember, resetDemo } from './data.js';
import { today, addMonths, membership, dateLabel, escapeHTML as esc, areaName } from './shared.js';
const $ = s => document.querySelector(s), root = $('#admin-root'), dialog = $('#admin-dialog');
let config, members = [], view = 'dashboard', filter = 'all', query = '', toastTimer;
const icons = { dashboard: '▦', clients: '☷', new: '+', subscriptions: '◷', gym: '▰', cf: '✳', settings: '⚙' };
const mark = `<img class="brand-logo" src="/assets/iron-panthers-logo.png" alt="" width="54" height="54"><span>IRON PANTHERS<small>ADMINISTRACIÓN</small></span>`;
function toast(message) { $('#toast').textContent = message; $('#toast').hidden = false; clearTimeout(toastTimer); toastTimer = setTimeout(() => $('#toast').hidden = true, 4200); }
function badge(m) { const status = membership(m); return `<span class="badge ${status.state}">${status.label}</span>`; }
function login(error = '') {
  root.innerHTML = `<main class="login-page"><a class="brand" href="/">${mark}</a><div class="login-panel"><p class="eyebrow">TU FAMILIA. TU ESPACIO.</p><h1 class="rough">TODO BAJO<br><span class="red">CONTROL.</span></h1><p>Clientes, modalidades y membresías.<br>El día a día de Iron Panthers, en un solo lugar.</p>${config?.mode === 'demo' ? `<div class="admin-demo-note"><strong>Demostración</strong><p>Los registros son de ejemplo y se guardan solo en este navegador. Usa datos ficticios para explorar.</p></div><button class="button full" id="enter-demo">Explorar administración</button>` : `<form id="login-form"><label for="user">Usuario</label><input id="user" name="user" autocomplete="username" required><label for="password">Contraseña</label><input id="password" name="password" type="password" autocomplete="current-password" required><p class="form-error" id="login-error" role="alert">${esc(error)}</p><button class="button full">Entrar al panel</button></form>`}<a href="/" class="back-to-site">Volver al portal de socios</a></div><div class="login-year" aria-hidden="true">2010</div></main>`;
  if (config?.mode === 'demo') $('#enter-demo').onclick = async () => { sessionStorage.setItem('iron_demo_entered', '1'); await openApp(); };
  else $('#login-form').onsubmit = async e => { e.preventDefault(); const button = e.target.querySelector('button'); button.disabled = true; $('#login-error').textContent = ''; try { await api('login', { user: $('#user').value, password: $('#password').value }); await openApp(); } catch (err) { $('#login-error').textContent = err.message; } finally { button.disabled = false; } };
}
async function refresh() { members = await listMembers(); }
async function openApp() { try { await refresh(); shell(); render(); } catch (e) { if (e.status === 401) login('Tu sesión terminó. Vuelve a entrar.'); else root.innerHTML = `<main class="loading-screen"><h1>No pudimos cargar el panel</h1><p>${esc(e.message)}</p><button class="button" id="retry">Intentar de nuevo</button><a href="/">Volver al portal</a></main>`; $('#retry')?.addEventListener('click', openApp); } }
function shell() {
  const nav = [['dashboard', 'Resumen'], ['clients', 'Clientes'], ['new', 'Registrar socio'], ['subscriptions', 'Membresías'], ['gym', 'Iron Gym'], ['cf', 'Iron Cross'], ['settings', 'Configuración']];
  root.innerHTML = `<aside class="admin-sidebar" id="admin-sidebar"><a class="brand" href="/">${mark}</a><p class="nav-label">TU ESPACIO</p><nav aria-label="Administración">${nav.map(([key, label]) => `<button data-nav="${key}"><span aria-hidden="true">${icons[key]}</span>${label}</button>`).join('')}</nav><div class="sidebar-bottom"><a href="/">Ver portal de socios</a><p>ORIGINALES DESDE 2010</p></div></aside><div class="admin-page"><header class="admin-header"><div><button id="sidebar-toggle" class="icon-button" aria-label="Abrir navegación" aria-controls="admin-sidebar" aria-expanded="false">☰</button><span id="breadcrumb">Administración / Resumen</span></div><div class="admin-user"><span class="mode-label">${config.mode === 'demo' ? 'DEMOSTRACIÓN' : 'EN LÍNEA'}</span><button id="logout">Salir</button><span class="admin-avatar" aria-hidden="true">IP</span></div></header><main id="admin-main"></main></div>`;
  root.querySelectorAll('[data-nav]').forEach(b => b.onclick = () => { const next = b.dataset.nav; filter = next === 'gym' || next === 'cf' ? next : 'all'; view = next === 'gym' || next === 'cf' ? 'clients' : next; query = ''; document.body.classList.remove('sidebar-open'); $('#sidebar-toggle').setAttribute('aria-expanded','false'); render(); window.scrollTo(0,0); });
  $('#sidebar-toggle').onclick = () => { const open = document.body.classList.toggle('sidebar-open'); $('#sidebar-toggle').setAttribute('aria-expanded', open); };
  $('#logout').onclick = async () => { try { if (config.mode === 'cloud') await api('logout', {}); sessionStorage.removeItem('iron_demo_entered'); members = []; login(); } catch (e) { toast(e.message); } };
}
const activeCount = () => members.filter(m => ['active','soon'].includes(membership(m).state)).length;
function dashboard() {
  const soon = members.filter(m => membership(m).state === 'soon').sort((a,b) => membership(a).days - membership(b).days);
  return `<div class="admin-title"><div><p class="eyebrow">EL DÍA EMPIEZA AQUÍ</p><h1>Tu equipo, <span class="red">en movimiento.</span></h1><p>${dateLabel(today())} · Así va Iron Panthers hoy.</p></div><button class="button" data-create>+ Registrar socio</button></div><div class="stats-grid">${[[members.length,'Socios registrados','◎'],[activeCount(),'Membresías vigentes','✓'],[soon.length,'Por vencer · 7 días','◷'],[members.filter(m=>membership(m).state==='expired').length,'Membresías vencidas','!']].map(([n,label,icon],i)=>`<div class="stat-card"><div><span>${label}</span><span aria-hidden="true">${icon}</span></div><strong ${i === 2 ? 'class="red"' : ''}>${n}</strong><small>${['La comunidad sigue creciendo','Listos para entrenar','Dales seguimiento','Una oportunidad de volver'][i]}</small></div>`).join('')}</div><div class="dashboard-columns"><section class="admin-card"><div class="card-heading"><h2>Próximos vencimientos</h2><button class="subtle" data-go-subs>Ver todas</button></div>${soon.length ? soon.slice(0,5).map(m=>`<button class="upcoming-row" data-view="${m.id}"><span class="initials">${esc(initials(m.name))}</span><span><b>${esc(m.name)}</b><small>${areaName(m.area)} · #${m.id}</small></span><span class="due">${membership(m).days === 0 ? 'Hoy' : membership(m).days + ' días'}</span></button>`).join('') : `<div class="empty"><span>✓</span><h3>Todo al día</h3><p>No hay membresías que venzan en los próximos siete días.</p></div>`}</section><section class="admin-card areas-summary"><div class="card-heading"><h2>Una familia, dos caminos</h2></div>${['gym','cf'].map(a=>`<button class="area-summary" data-area-filter="${a}"><span class="area-symbol">${a==='gym'?'▰':'✳'}</span><div><strong>${areaName(a)}</strong><small>${a==='gym'?'Fuerza a tu ritmo':'Energía en comunidad'}</small></div><b>${members.filter(m=>m.area===a).length}</b></button>`).join('')}<div class="admin-motto"><span class="rough">LA FUERZA<br>SE COMPARTE.</span><small>IRON PANTHERS · EST. 2010</small></div></section></div>`;
}
function initials(name) { return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase(); }
function filtered() { const q = query.toLocaleLowerCase('es-MX').normalize('NFD').replace(/[\u0300-\u036f]/g,''); return members.filter(m => (filter==='all' || m.area===filter || membership(m).state===filter) && (!q || (m.name.toLocaleLowerCase('es-MX').normalize('NFD').replace(/[\u0300-\u036f]/g,'')+' '+m.id).includes(q))); }
function rows() {
  const list = filtered();
  if (!list.length) return `<div class="empty"><span>◎</span><h3>${members.length ? 'Sin coincidencias' : 'Tu familia empieza aquí'}</h3><p>${members.length ? 'Prueba otro nombre, número o filtro.' : 'Registra al primer socio para comenzar.'}</p>${!members.length ? '<button class="button" data-create>Registrar socio</button>' : ''}</div>`;
  return `<div class="table-scroll"><table><thead><tr><th>Socio</th><th>Modalidad</th><th>Vencimiento</th><th>Estado</th><th><span class="sr-only">Acciones</span></th></tr></thead><tbody>${list.map(m=>`<tr><td><div class="table-person"><span class="initials">${esc(initials(m.name))}</span><div><strong>${esc(m.name)}</strong><small>#${m.id} · ${m.age} años</small></div></div></td><td data-label="Modalidad"><span class="area-label ${m.area}">${areaName(m.area)}</span></td><td data-label="Vencimiento">${dateLabel(membership(m).end)}<small>${m.months} ${m.months===1?'mes':'meses'}</small></td><td data-label="Estado">${badge(m)}</td><td><div class="row-actions"><button data-view="${m.id}" aria-label="Ver ${esc(m.name)}">Ver</button><button data-edit="${m.id}" aria-label="Editar ${esc(m.name)}">Editar</button><button class="delete-action" data-delete="${m.id}" aria-label="Eliminar ${esc(m.name)}">×</button></div></td></tr>`).join('')}</tbody></table></div><div class="table-bottom">${list.length} de ${members.length} socios</div>`;
}
function clients(subscriptions = false) { return `<div class="admin-title"><div><p class="eyebrow">${subscriptions?'MANTÉN EL RITMO':'LA COMUNIDAD IRON'}</p><h1>${subscriptions?'Membresías':filter==='gym'?'Iron Gym':filter==='cf'?'Iron Cross':'Nuestros socios'}</h1><p>${subscriptions?'Vigencia y seguimiento de cada membresía.':'Cada nombre, una historia de esfuerzo.'}</p></div><button class="button" data-create>+ Registrar socio</button></div><section class="admin-card client-list"><div class="list-toolbar"><label class="search-label" for="search"><span aria-hidden="true">⌕</span><input id="search" type="search" placeholder="Buscar nombre o número de socio" value="${esc(query)}"></label><button class="button secondary small" id="refresh">Actualizar</button></div><div class="filters" aria-label="Filtrar socios">${[['all','Todos'],['gym','Iron Gym'],['cf','Iron Cross'],['active','Activas'],['soon','Por vencer'],['expired','Vencidas'],['pending','Por iniciar']].map(([key,label])=>`<button data-filter="${key}" aria-pressed="${filter===key}">${label}</button>`).join('')}</div><div id="members-table">${rows()}</div></section>`; }
function form(member = {}) { return `<form id="member-form" class="member-form"><div class="form-section-label">01 / DATOS DEL SOCIO</div><div class="form-grid"><div class="wide"><label for="name">Nombre completo</label><input id="name" name="name" value="${esc(member.name||'')}" minlength="3" maxlength="100" autocomplete="name" required></div><div><label for="age">Edad</label><input id="age" name="age" type="number" min="12" max="100" value="${member.age||''}" required></div><div><label for="area">Modalidad</label><select id="area" name="area"><option value="gym" ${member.area==='gym'?'selected':''}>Iron Gym</option><option value="cf" ${member.area==='cf'?'selected':''}>Iron Cross</option></select></div></div><div class="form-section-label">02 / MEMBRESÍA</div><div class="form-grid"><div><label for="start">Fecha de inicio</label><input id="start" name="start" type="date" value="${member.start||today()}" min="2000-01-01" max="2100-12-31" required></div><div><label for="months">Duración</label><select id="months" name="months">${[1,3,6,12].map(n=>`<option value="${n}" ${(member.months||1)===n?'selected':''}>${n} ${n===1?'mes':'meses'}</option>`).join('')}</select></div></div><div class="form-preview" id="form-preview"></div><p id="save-error" class="form-error" role="alert"></p><div class="form-actions"><button type="button" class="button secondary" data-cancel>Cancelar</button><button type="submit" class="button">Guardar ${member.id?'cambios':'socio'}</button></div></form>`; }
function settings() { return `<div class="admin-title"><div><p class="eyebrow">ASÍ FUNCIONA TU ESPACIO</p><h1>Configuración</h1></div></div><section class="admin-card settings-card"><h2>${config.mode==='demo'?'Demostración local':'Datos compartidos en línea'}</h2><p>${config.mode==='demo'?'Los cambios se guardan en este navegador. En otro celular o computadora verás sus propios datos de prueba. Usa únicamente información ficticia.':'Los registros se comparten entre administración y el portal. Cada socio consulta su membresía con su número y código personal.'}</p>${config.mode==='demo'?'<p>Para usar registros reales, sigue la sección «Activar membresías en línea» de LEEME.md incluida en el proyecto.</p><hr><h3>Restaurar ejemplos</h3><p>Reemplaza los registros de prueba de este navegador por los seis socios originales.</p><button class="button secondary" id="reset-demo">Restaurar demostración</button>':'<p>La sesión administrativa dura ocho horas. Las credenciales se administran desde las variables de entorno de Vercel.</p>'}</section>`; }
function render() {
  const title = { dashboard:'Resumen',clients:'Clientes',new:'Registrar socio',subscriptions:'Membresías',settings:'Configuración' }[view]; $('#breadcrumb').textContent = 'Administración / ' + title;
  root.querySelectorAll('[data-nav]').forEach(b => { const selected = b.dataset.nav === (view==='clients'&&['gym','cf'].includes(filter)?filter:view); b.classList.toggle('selected',selected); selected ? b.setAttribute('aria-current','page') : b.removeAttribute('aria-current'); });
  $('#admin-main').innerHTML = view==='dashboard'?dashboard():view==='clients'||view==='subscriptions'?clients(view==='subscriptions'):view==='new'?`<div class="admin-title"><div><p class="eyebrow">BIENVENIDO A LA FAMILIA</p><h1>Registrar socio</h1><p>Todo listo para su próximo entrenamiento.</p></div></div><section class="admin-card registration-card">${form()}</section>`:settings();
  wireActions($('#admin-main'));
  if(view==='new') wireForm($('#admin-main'),{},false);
  $('#search')?.addEventListener('input',e=>{query=e.target.value;$('#members-table').innerHTML=rows();wireActions($('#members-table'));});
  document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#members-table').innerHTML=rows();wireActions($('#members-table'));});
  $('#refresh')?.addEventListener('click',async e=>{e.target.disabled=true;try{await refresh();render();toast('Lista actualizada.');}catch(err){handleError(err);}finally{e.target.disabled=false;}});
  $('#reset-demo')?.addEventListener('click',()=>confirmAction('¿Restaurar la demostración?','Se reemplazarán los registros de prueba de este navegador.',async()=>{await resetDemo();await refresh();render();toast('Demostración restaurada.');}));
}
function wireActions(scope) {
  scope.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>{view='new';render();window.scrollTo(0,0);});
  scope.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>details(Number(b.dataset.view)));
  scope.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(Number(b.dataset.edit)));
  scope.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const m=members.find(x=>x.id===+b.dataset.delete);confirmAction('¿Eliminar socio?',`Se eliminará el registro de ${m.name}. Esta acción no se puede deshacer.`,async()=>{await deleteMember(m.id);await refresh();render();toast('Socio eliminado.');});});
  scope.querySelectorAll('[data-area-filter]').forEach(b=>b.onclick=()=>{view='clients';filter=b.dataset.areaFilter;render();});
  scope.querySelector('[data-go-subs]')?.addEventListener('click',()=>{view='subscriptions';filter='soon';render();});
}
function openDialog(html) { dialog.innerHTML=`<button class="dialog-close icon-button" aria-label="Cerrar">×</button>${html}`; if(!dialog.open)dialog.showModal();document.body.classList.add('modal-open');dialog.querySelector('.dialog-close').onclick=()=>dialog.close(); }
dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));
function edit(id, renew=false) { const m=members.find(x=>x.id===id);openDialog(`<p class="eyebrow">SOCIO #${m.id}</p><h2>${renew?'Renovar membresía':'Editar socio'}</h2>${renew?'<p class="renew-note">Inicia un nuevo periodo desde la fecha elegida. Se reemplazará el periodo anterior.</p>':''}${form(renew?{...m,start:today(),months:1}:m)}`);wireForm(dialog,m,true); }
function wireForm(scope,member,isDialog) {
  const f=scope.querySelector('#member-form');
  function preview(){const start=f.elements.start.value,months=Number(f.elements.months.value);if(!start)return;try{scope.querySelector('#form-preview').innerHTML=`<span>VENCIMIENTO PREVISTO</span><strong>${dateLabel(addMonths(start,months))}</strong>`;}catch{scope.querySelector('#form-preview').textContent='Revisa la fecha.';}}
  f.elements.start.onchange=preview;f.elements.months.onchange=preview;preview();
  f.querySelector('[data-cancel]').onclick=()=>{if(isDialog)dialog.close();else{view='clients';render();}};
  f.onsubmit=async e=>{e.preventDefault();const button=f.querySelector('[type=submit]');button.disabled=true;scope.querySelector('#save-error').textContent='';try{const data=Object.fromEntries(new FormData(f));if(member.id)data.id=member.id;const saved=await saveMember(data);await refresh();if(isDialog)dialog.close();view='clients';filter='all';query='';render();toast(member.id?'Cambios guardados.':'Socio registrado. Comparte su código de acceso.');if(!member.id)details(saved.id);}catch(err){scope.querySelector('#save-error').textContent=err.message;}finally{button.disabled=false;}};
}
function details(id) { const m=members.find(x=>x.id===id),s=membership(m);openDialog(`<p class="eyebrow">SOCIO #${id}</p><h2>${esc(m.name)}</h2>${badge(m)}<dl class="detail-grid"><div><dt>Modalidad</dt><dd>${areaName(m.area)}</dd></div><div><dt>Edad</dt><dd>${m.age} años</dd></div><div><dt>Inicio</dt><dd>${dateLabel(m.start)}</dd></div><div><dt>Vencimiento</dt><dd>${dateLabel(s.end)}</dd></div></dl><div class="access-card"><p class="eyebrow">ACCESO PERSONAL AL PORTAL</p><div><strong>${esc(m.access_code)}</strong><button class="subtle" id="copy-code">Copiar acceso</button></div><small>Comparte este código únicamente con el socio.</small></div><div class="form-actions"><button class="button secondary" id="detail-edit">Editar datos</button><button class="button" id="detail-renew">Renovar</button></div>`);$('#detail-edit').onclick=()=>edit(id);$('#detail-renew').onclick=()=>edit(id,true);$('#copy-code').onclick=async()=>{try{await navigator.clipboard.writeText(`IRON PANTHERS\nSocio: ${id}\nCódigo: ${m.access_code}\nPortal: ${location.origin}/#membresia`);toast('Acceso copiado.');}catch{toast('Selecciona y copia el código que aparece en pantalla.');}}; }
function confirmAction(title,description,action){openDialog(`<h2>${esc(title)}</h2><p class="confirm-description">${esc(description)}</p><p class="form-error" id="confirm-error" role="alert"></p><div class="form-actions"><button class="button secondary" id="confirm-cancel">Cancelar</button><button class="button" id="confirm-yes">Confirmar</button></div>`);$('#confirm-cancel').onclick=()=>dialog.close();$('#confirm-yes').onclick=async e=>{e.target.disabled=true;try{await action();dialog.close();}catch(err){$('#confirm-error').textContent=err.message;}finally{e.target.disabled=false;}};}
function handleError(e){if(e.status===401)login('Tu sesión terminó. Vuelve a entrar.');else toast(e.message);}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('sidebar-open');$('#sidebar-toggle')?.setAttribute('aria-expanded','false');}});
async function start(){try{config=await getConfig();if(config.mode==='demo'){if(sessionStorage.getItem('iron_demo_entered'))await openApp();else login();}else{const s=await api('session');s.authenticated?await openApp():login();}}catch(e){root.innerHTML=`<main class="loading-screen"><h1>No se pudo conectar</h1><p>${esc(e.message)}</p><button class="button" id="retry-start">Reintentar</button><a href="/">Volver al portal</a></main>`;$('#retry-start').onclick=start;}}
start();
